import { LearningModule } from "./types";

export const anomalyDetection: LearningModule = {
  id: "anomaly-detection",
  title: "Anomaly Detection",
  category: "Anomaly Detection",
  prerequisites: ["clustering"],
  tracks: ["practitioner"],
  difficulty: 2,
  estimatedMinutes: 35,
  shortDescription: "Methods for identifying rare, unusual observations in datasets, including statistical thresholding, tree-based isolation, and distance-based scoring.",
  learningObjectives: [
    "Identify different types of anomalies including point, collective, and contextual anomalies.",
    "Formulate and apply statistical thresholds using Z-scores and Interquartile Range (IQR).",
    "Explain the mechanics of the Isolation Forest algorithm and how path lengths translate to anomaly scores.",
    "Contrast supervised learning and unsupervised anomaly detection in terms of label imbalance.",
    "Evaluate anomaly detection models using precision-at-k and recall-at-review-capacity metrics."
  ],
  keyTerms: [
    {
      term: "Anomaly (Outlier)",
      definition: "An observation that deviates so significantly from other observations as to arouse suspicion that it was generated by a different mechanism."
    },
    {
      term: "Isolation Forest",
      definition: "An unsupervised anomaly detection algorithm that isolates observations by randomly partitioning feature space using binary trees; anomalies are isolated closer to the root."
    },
    {
      term: "Contamination Ratio",
      definition: "A hyperparameter specifying the expected proportion of outliers in the dataset, used to set the decision threshold."
    },
    {
      term: "Z-score Thresholding",
      definition: "A statistical outlier detection method where values that are more than a certain number of standard deviations (usually 3) from the mean are flagged."
    }
  ],
  workedExamples: [
    {
      title: "IQR-Based Outlier Detection",
      problem: "Given a feature vector of observations $X = [12, 14, 15, 18, 19, 22, 23, 48]$, calculate the first quartile $Q_1$, the third quartile $Q_3$, the Interquartile Range ($IQR$), and determine if any observations are outliers according to the IQR rule.",
      solution: "First, find the quartiles of the sorted data (using standard interpolation methods):\n- The median is: $\\frac{19 + 22}{2} = 20.5$.\n- The first quartile $Q_1$ (median of the lower half $[12, 14, 15, 18]$) is: $\\frac{14 + 15}{2} = 14.5$.\n- The third quartile $Q_3$ (median of the upper half $[19, 22, 23, 48]$) is: $\\frac{22 + 23}{2} = 22.5$.\n\nCalculate the IQR:\n$$IQR = Q_3 - Q_1 = 22.5 - 14.5 = 8.0$$\n\nCalculate the outlier threshold boundaries:\n- Lower bound: $Q_1 - 1.5 \\times IQR = 14.5 - 1.5 \\times 8.0 = 14.5 - 12.0 = 2.5$\n- Upper bound: $Q_3 + 1.5 \\times IQR = 22.5 + 1.5 \\times 8.0 = 22.5 + 12.0 = 34.5$\n\nCheck the dataset values against these boundaries:\n- All values are above $2.5$.\n- The value $48$ is greater than $34.5$.\n\nTherefore, $48$ is flagged as an outlier."
    }
  ],
  misconceptions: [
    {
      claim: "Anomaly detection is simply a binary classification problem with a highly imbalanced dataset.",
      correction: "Supervised classification requires clear labels for all classes and assumes the test distribution matches the training distribution. Unsupervised anomaly detection is used when outliers are unlabeled, rare, and potentially represent completely unseen patterns (novelties) that cannot be learned in a supervised manner."
    },
    {
      claim: "If you remove outliers during data cleaning, you are performing anomaly detection.",
      correction: "Data cleaning removes noise to improve training quality for downstream models. Anomaly detection is the primary task of interest, where identifying the outliers themselves is the goal (e.g. credit card fraud, industrial equipment failures)."
    }
  ],
  references: [
    {
      title: "Outlier Analysis (2nd ed.)",
      authors: "Charu C. Aggarwal",
      url: "https://link.springer.com/book/10.1007/978-3-319-47578-3",
      type: "textbook"
    },
    {
      title: "Isolation Forest",
      authors: "Fei Tony Liu, Kai Ming Ting, and Zhi-Hua Zhou",
      url: "https://ieeexplore.ieee.org/document/4781136",
      type: "paper"
    }
  ],
  failureModes: [
    {
      name: "Masking Effect",
      description: "When multiple outliers cluster close together, distance-based methods fail to flag them because they serve as neighbors to one another, making them look like normal data clusters.",
      mitigation: "Use density-based algorithms (like LOF) or projection-based methods (like Isolation Forest) that do not rely purely on global distances."
    }
  ],
  pros: [
    "Crucial for identifying high-risk events (fraud, cyber attacks) where labels are unavailable.",
    "Isolation Forests scale linearly to high-dimensional datasets.",
    "Unsupervised algorithms can identify novel anomaly types that have never occurred before."
  ],
  cons: [
    "Highly sensitive to the specified contamination ratio hyperparameter.",
    "Evaluating unsupervised models is extremely difficult without at least a small labeled validation set.",
    "Prone to high false-alarm rates in noisy datasets."
  ],
  intuition: "Imagine you're checking a list of credit card transactions. Most are for 15, 30, or 60 dollars at local stores. Suddenly, there's a transaction for 3000 dollars in another country. That transaction is an anomaly. Anomaly detection is about building models that can automatically spot these odd patterns. Some look at statistics (Z-scores), some look at distance (how far is a point from any cluster), and some look at isolation: if you randomly divide your dataset by drawing lines, it takes many cuts to isolate a normal point in a dense cluster, but a lone outlier can be isolated in just a few cuts. This path-length difference is how an Isolation Forest flags outliers.",
  mathematics: "### Z-score Outlier Thresholding\n\nFor a normally distributed feature $X$ with mean $\\mu$ and standard deviation $\\sigma$, the Z-score for a data point $x_i$ is:\n$$z_i = \\frac{x_i - \\mu}{\\sigma}$$\n\nA point is flagged as an anomaly if $|z_i| > \tau$, where $\tau$ is typically set to $3.0$ (representing the $99.73\\%$ boundary).\n\n### Isolation Forest Anomaly Score\n\nAn Isolation Forest isolates instances by recursively partitioning features. Anomalies require fewer partitions. The anomaly score $s(x, n)$ for a sample $x$ over a dataset of size $n$ is:\n$$s(x, n) = 2^{-\\frac{E(h(x))}{c(n)}}$$\nwhere $E(h(x))$ is the average path length (number of splits required to isolate $x$) across a forest of isolation trees, and $c(n)$ is the average path length of an unsuccessful search in a Binary Search Tree (BST) built from $n$ nodes:\n$$c(n) = 2\\ln(n - 1) + 0.5772156649 - \\frac{2(n - 1)}{n}$$\n\n- If $E(h(x)) \\to 0$, then $s \\to 1$: the instance is highly anomalous (isolated very quickly near the root).\n- If $E(h(x)) \\to n-1$, then $s \\to 0$: the instance is a normal inlier.\n\n### Distance-Based Outlier Score\n\nLet $d(\\mathbf{x}_i, k)$ represent the Euclidean distance from $\\mathbf{x}_i$ to its $k$-th nearest neighbor. The outlier score is simply the distance value:\n$$\\text{Score}(\\mathbf{x}_i) = d(\\mathbf{x}_i, k)$$\nPoints with large neighbor distances are flagged as anomalies.",
  fullDescription: "Anomaly detection is the identification of rare items, events, or observations which raise suspicions by differing significantly from the majority of the data. It finds applications in a wide variety of domains, including cyber-intrusion detection, fraud detection, fault detection, system health monitoring, and data preprocessing pipelines.",
  codeSnippet: `/**
 * Simple k-th Nearest Neighbor Outlier Detector (Distance-based)
 */
export class KNNOutlierDetector {
  private trainData: number[][] = [];

  constructor(private k: number = 3) {}

  fit(data: number[][]) {
    this.trainData = data.map(row => [...row]);
  }

  /**
   * Computes Euclidean distance between two vectors
   */
  private euclideanDistance(v1: number[], v2: number[]): number {
    return Math.sqrt(v1.reduce((sum, val, idx) => sum + Math.pow(val - v2[idx], 2), 0));
  }

  /**
   * Scores a query point based on distance to its k-th nearest neighbor
   */
  score(query: number[]): number {
    if (this.trainData.length === 0) return 0;

    // Compute distances to all points in training data
    const distances = this.trainData.map(point => this.euclideanDistance(query, point));
    
    // Sort distances in ascending order
    distances.sort((a, b) => a - b);
    
    // The anomaly score is the distance to the k-th nearest neighbor
    // Handle cases where training set size is smaller than k
    const targetIdx = Math.min(this.k - 1, distances.length - 1);
    return distances[targetIdx];
  }

  /**
   * Predicts anomalies based on a threshold value
   */
  predict(query: number[], threshold: number): boolean {
    return this.score(query) > threshold;
  }
}`,
  relatedModules: ["clustering", "evaluation-metrics", "data-preparation"]
};
